### ISSUE TITLE
IDA运行entrance.py报错

### ISSUE THREAD

**Issue by Su-Dream** [nyaoouo/IdaFFxivOpcodes#1]
`C:\fptlitem\ldaFFxivOpcodes\entrance.py: in method 'get bytes', argument 2 of type 'unsigned int'
raceback(most recent call last):
File "C:\fpt\ida\pythonl3\ida idaapi,py", line 616, in lDAPython ExecScript
exec(code,g)
File "C:/fpt/item/ldaFFxivOpcodes/entrance.py", line 20, in <module>
main(False)
File "C:/fpt/item/ldaFFxivOpcodes/entrance.py", line 13, in mainimport opcode finder
File "C:\fpt/item/ldaFFxivOpcodes\opcode finder init .py", line 5, in <module>from .utils import*
File "C:\fpt/item/ldaFFxivOpcodes\opcode finder\utils\ init .py", line 5, in <module>from .pattern import*File "C:\fpt/item/ldaFFxivOpcodes\opcode finder\utils\pattern.py", line 8, in <module>game data=get bytes(min ea, max ea-min ea)File "C:\fpt\ida\python\3\ida bytes,py", line 4772, in get bytesreturn ida bytes.get bytes(*args)OverflowError: in method 'get bytes', argument 2 of type 'unsigned int'
`

![image](https://github.com/user-attachments/assets/ea2f5df7-b093-4490-8c6e-28bea00ed0c2)

**Comment by nyaoouo** [comment]
一，问题依然存在吗
二，ida版本
三，python版本

**Comment by Su-Dream** [comment]
感谢答复
问题依然存在
ida版本7.6pro非直装版
Python 3.10.0

**Comment by nyaoouo** [comment]
> 感谢答复 问题依然存在 ida版本7.6pro非直装版 Python 3.10.0

换ida9/8试试，7我好久没用过了

**Comment by Su-Dream** [comment]
感谢答复
IDA9.0pro | python3.10.0
有新报错
![image](https://github.com/user-attachments/assets/8d97ec5f-e8e6-4627-af5b-789dea1f3800)
`
 error: Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "<string>", line 13, in main
  File "C:\fpt/item/IdaFFxivOpcodes\opcode_finder\__init__.py", line 5, in <module>
    from .utils import *
  File "C:\fpt/item/IdaFFxivOpcodes\opcode_finder\utils\__init__.py", line 5, in <module>
    from .pattern import *
  File "C:\fpt/item/IdaFFxivOpcodes\opcode_finder\utils\pattern.py", line 8, in <module>
    game_data = get_bytes(min_ea, max_ea - min_ea)
  File "C:\fpt\ida\ida9.0\python\ida_bytes.py", line 4352, in get_bytes
    return _ida_bytes.get_bytes(ea, size, gmb_flags)
TypeError: Wrong number or type of arguments for overloaded function 'get_bytes'.
  Possible C/C++ prototypes are:
    py_get_bytes(ea_t,unsigned int,int)
    py_get_bytes(ea_t,unsigned int)
`
效果复现
File -> Script File -> Select 'entrance.py' 
IdaFFxivOpcodes是最新main分支
